import Head from 'next/head'
import '@/styles/Home.module.css'

import { Inter } from '@next/font/google'
import Header from '@/components/Header'
import { useConnect, useAccount } from "wagmi";
import { MetaMaskConnector } from "wagmi/connectors/metaMask";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { address, isConnected } = useAccount();
  const { connect } = useConnect({
    connector: new MetaMaskConnector(),
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href="https://fonts.cdnfonts.com/css/clash-display" rel="stylesheet"></link> */}
      </Head>
      <main>
      <Header connect={connect} isConnected={isConnected} address={address}  />
        <div>
          
            main

        </div>
      </main>
    </>
  )
}
