import Head from 'next/head'
import Swap from './routes/Swap'
import { Inter } from '@next/font/google'
import { useConnect, useAccount } from "wagmi";



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { address, isConnected } = useAccount();

  return (
    <>
      <Head>
        <title>Moralis Dex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href="https://fonts.cdnfonts.com/css/clash-display" rel="stylesheet"></link> */}
      </Head>
      <main className='mainWindow'>
        <Swap isConnected={isConnected} address={address} />
      </main>
    </>
  )
}
